### ISSUE TITLE
Errors when updating average rating for tours 

### ISSUE THREAD

**Issue by vt0022** [htien120802/booking-travel#1]
Error starts from **reviewModel.js** in middleware using for **pre findOne**:
```
// findByIdAndUpdate
// findByIdAndDelete
// reviewSchema.pre(/^findOneAnd/, async function (next) {
//   this.r = await this.findOne();
//   console.log(this.r);
//   next();
// });
```
When updating a review with endpoint **`/api/v1/reviews/:reviewId`**, it always throwing this:
`Query was already executed: Review.findOne(...)`
So avarage rating cannot be updated.

**Comment by htien120802** [comment]
Try to change **this.findOne()** to **this.clone().findOne()**
